name: RealisticBiomes
main: com.untamedears.realisticbiomes.RealisticBiomes
version: 0.06.02
authors: [ttk2, Wehttam664, nrfs] # Not sure who the authors are here. Assuming ttk2, myself, and latest contributor.
